---
title: 'Ch 3: Linear Regression'
author: "Varun Varanasi"
date: "7/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading Packages and Data

```{r}
library(MASS)
library(ISLR)
```

## Working with the Boston Dataset
```{r}
?Boston
```

## Running Simple Linear Regression 
```{r}
lm.fit = lm(medv ~ lstat, data= Boston)
summary(lm.fit)
```

## Retrieving SLR coefficients 

```{r}
names(lm.fit)

coef(lm.fit)
```

## Confidence Intervals
```{r}
confint(lm.fit)
```

## Confidence and Prediction Intervals 
```{r}
predict(lm.fit, data.frame(lstat= c(5,10,15)), interval = "confidence")
```

```{r}
predict(lm.fit, data.frame(lstat= c(5,10,15)), interval = "prediction")
```

## Plotting 
```{r}
attach(Boston)
plot(lstat, medv)
abline(lm.fit)
```

```{r}
par ( mfrow =c(2 ,2) )
plot(lm.fit )
```

```{r}
plot( predict (lm.fit ), residuals (lm.fit ))
plot( predict (lm.fit ), rstudent (lm.fit ))
```
Appears to be some unexplained relationship

## Multiple Linear Regression